model_list:
  - model_name: azure-gpt-4o
    litellm_params:
      model: os.environ/AZURE_DEPLOYMENT_NAME
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY
      api_version: os.environ/AZURE_API_VERSION

guardrails:
  - guardrail_name: azure-prompt-shield
    litellm_params:
      guardrail: azure/prompt_shield
      mode: pre_call 
      api_key: os.environ/AZURE_GUARDRAIL_API_KEY
      api_base: os.environ/AZURE_GUARDRAIL_API_BASE 
  - guardrail_name: azure-text-moderation
    litellm_params:
      guardrail: azure/text_moderations
      mode: [pre_call] 
      api_key: os.environ/AZURE_GUARDRAIL_API_KEY
      api_base: os.environ/AZURE_GUARDRAIL_API_BASE 
      default_on: true

litellm_settings:
  callbacks: ["opik"]
  OPIK_URL_OVERRIDE : os.environ/OPIK_URL_OVERRIDE
  OPIK_PROJECT_NAME : os.environ/OPIK_PROJECT_NAME
